DROP DATABASE IF EXISTS `HOTELES_RED`;

CREATE DATABASE `HOTELES_RED`;

USE	`HOTELES_RED`;

CREATE TABLE `DEPARTAMENTO`(
	`ID_Departamento` INTEGER PRIMARY KEY,
    `nombre` VARCHAR(100)
);

CREATE TABLE `CUARTO`(
	`NUMERO_CUARTO` INTEGER,
	`piso` INTEGER,
    `CODIGO_HOTEL` INTEGER,
    `numero_camas` INTEGER,
	PRIMARY KEY(`NUMERO_CUARTO`, `CODIGO_HOTEL`)
);

CREATE TABLE `D_ESTANDAR`(
	`NUMERO_CUARTO` INTEGER PRIMARY KEY
);

CREATE TABLE `D_LUJO`(
	`NUMERO_CUARTO` INTEGER PRIMARY KEY,
    `tarifa_anticipada` INTEGER
);

CREATE TABLE `D_SUPERLUJO`(
	`NUMERO_CUARTO` INTEGER PRIMARY KEY,
    `SIN/CON balcon` VARCHAR(20),
    `tarifa_anticipada` INTEGER
);

CREATE TABLE `HOTEL`(
	`CODIGO_HOTEL` INTEGER,
    `ID_DEPARTAMENTO` INTEGER,
    `nombre` VARCHAR(100),
    `direccion` VARCHAR(100),
    PRIMARY KEY(`CODIGO_HOTEL`, `ID_DEPARTAMENTO`)
);

CREATE TABLE `AMENIDADES`(
	`nombre` varchar(100),
    `NUMERO_CUARTO` INTEGER,
    `ID_AMENIDADES` INTEGER,
	PRIMARY KEY(`ID_AMENIDADES`,`NUMERO_CUARTO`)
);

CREATE TABLE `TELEFONO_CLIENTE`(
	`ID_CLIENTE` INTEGER PRIMARY KEY,
    `telefono` VARCHAR(10)
);

CREATE TABLE `CUARTO_RESERVA`(
	`NUMERO_CUARTO` INTEGER,
     `ID_RESERVA`	INTEGER,
     `CODIGO_HOTEL` INTEGER,
     `ID_CLIENTE` INTEGER,
	`valor_pagado` INTEGER,
    `fecha` DATE,
    `hora_entrada` TIME,
    `hora_salida` TIME,
    PRIMARY KEY(
		`NUMERO_CUARTO`, `ID_RESERVA`,
        `CODIGO_HOTEL`, `ID_CLIENTE`
    )
);

CREATE TABLE `CLIENTE`(
	`ID_CLIENTE` INTEGER,
    `nombre` VARCHAR(100),
    `primer_apellido`VARCHAR(100),
    `segundo_apellido`VARCHAR(100),
    `CODIGO_HOTEL` INTEGER,
    PRIMARY KEY(`ID_CLIENTE`,`CODIGO_HOTEL`)
);

CREATE TABLE `RESERVA`(
	`ID_RESERVA` INTEGER,
    `ID_CLIENTE` INTEGER,
    `inicio_reserva` INTEGER,
    `cantidad_dias` INTEGER,
    `fecha_reserva` DATE,
	PRIMARY KEY(`ID_RESERVA`,`ID_CLIENTE`)
);

CREATE TABLE `CLIENTE_NACIONAL`(
	`ID_CLIENTE` INTEGER PRIMARY KEY,
	`dni` INTEGER
);

CREATE TABLE `CLIENTE_EXTRANJERO`(
	`ID_CLIENTE` INTEGER PRIMARY KEY,
    `pasaporte` INTEGER,
    `pais` VARCHAR(100)
);

ALTER TABLE `HOTEL` ADD FOREIGN KEY (ID_Departamento) REFERENCES `DEPARTAMENTO`(`ID_DEPARTAMENTO`);
ALTER TABLE `CUARTO` ADD FOREIGN KEY (CODIGO_HOTEL) REFERENCES `HOTEL`(`CODIGO_HOTEL`);
ALTER TABLE `CLIENTE` ADD FOREIGN KEY (CODIGO_HOTEL) REFERENCES `HOTEL`(`CODIGO_HOTEL`);
ALTER TABLE `TELEFONO_CLIENTE` ADD FOREIGN KEY (ID_CLIENTE) REFERENCES `CLIENTE`(`ID_CLIENTE`);
ALTER TABLE `RESERVA` ADD FOREIGN KEY (ID_CLIENTE) REFERENCES `CLIENTE`(`ID_CLIENTE`);
ALTER TABLE `D_ESTANDAR` ADD FOREIGN KEY (NUMERO_CUARTO) REFERENCES `CUARTO`(`NUMERO_CUARTO`);
ALTER TABLE `D_LUJO` ADD FOREIGN KEY (NUMERO_CUARTO) REFERENCES `CUARTO`(`NUMERO_CUARTO`);
ALTER TABLE `D_SUPERLUJO` ADD FOREIGN KEY (NUMERO_CUARTO) REFERENCES `CUARTO`(`NUMERO_CUARTO`);
ALTER TABLE `CUARTO_RESERVA` ADD FOREIGN KEY (NUMERO_CUARTO) REFERENCES `CUARTO`(`NUMERO_CUARTO`);
ALTER TABLE `CUARTO_RESERVA` ADD FOREIGN KEY (CODIGO_HOTEL) REFERENCES `CUARTO`(`CODIGO_HOTEL`);
ALTER TABLE `AMENIDADES` ADD FOREIGN KEY (NUMERO_CUARTO) REFERENCES `CUARTO`(`NUMERO_CUARTO`);
ALTER TABLE `CUARTO_RESERVA` ADD FOREIGN KEY (ID_RESERVA) REFERENCES `RESERVA`(`ID_RESERVA`);
ALTER TABLE `CUARTO_RESERVA` ADD FOREIGN KEY (ID_CLIENTE) REFERENCES `RESERVA`(`ID_CLIENTE`);
ALTER TABLE `CLIENTE_NACIONAL` ADD FOREIGN KEY (ID_CLIENTE) REFERENCES `CLIENTE`(`ID_CLIENTE`);
ALTER TABLE `CLIENTE_EXTRANJERO` ADD FOREIGN KEY (ID_CLIENTE) REFERENCES `CLIENTE`(`ID_CLIENTE`);


